stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: |-
        mvn clean install  -Dmaven.test.skip=true -s settings.xml
        pwd
        cat /etc/hostname
        df -h
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/springboot-s2i:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.xk12.cn
